---
apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-a
  name: app-a
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
        service-mesh: enabled
    spec:
      # initContainers:
      # - name: proxy-init
      #   image: diy-sm-proxy-init
      #   imagePullPolicy: IfNotPresent
      #   securityContext:
      #     capabilities:
      #       add:
      #         - NET_ADMIN
      #         - NET_RAW
      #       drop:
      #         - ALL
      containers:
      # - name: proxy
      #   image: diy-sm-proxy
      #   imagePullPolicy: IfNotPresent
      #   securityContext:
      #     runAsUser: 1337
      - name: app-a
        image: diy-sm-app-a
        imagePullPolicy: IfNotPresent
