---
apiVersion: v1
kind: Namespace
metadata:
  name: service-mesh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: service-mesh
  name: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: service-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service-mesh
  name: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: diy-sm-controller
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: service-mesh
  name: controller
spec:
  selector:
    app: controller
  ports:
  - port: 8080
    targetPort: 8080
