---
apiVersion: v1
kind: Namespace
metadata:
  name: http-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: http-client
  name: http-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: http-client
  name: http-client
  labels:
    app: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
        service-mesh: enabled
    spec:
      serviceAcountName: http-client
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: http-client
        image: diy-sm-http-client
        imagePullPolicy: IfNotPresent
        env:
        - name: ENDPOINT
          value: "http://http-server.http-server.svc.cluster.local./hello"
